#!/usr/bin/env php
<?php
use Base\SkelsusCommandProviderInterface;
use Symfony\Component\Console\Application;
use Zend\Mvc\Application as MvcApplication;
use Zend\Stdlib\ArrayUtils;

require 'vendor/autoload.php';

// Setup the Zend Framework application
$appConfig = require __DIR__ . '/config/application.config.php';
if (file_exists(__DIR__ . '/config/development.config.php')) {
    $appConfig = ArrayUtils::merge($appConfig, require __DIR__ . '/config/development.config.php');
}

$zfApplication = MvcApplication::init($appConfig);
$serviceManager = $zfApplication->getServiceManager();
$moduleManager  = $serviceManager->get('ModuleManager');

// Setup the Symfony application
$application = new Application('skelsus-zf3');

// Look for Modules providing Commands
foreach ($moduleManager->getLoadedModules() as $module) {
    if ($module instanceof SkelsusCommandProviderInterface) {
        $commands = $module->getSkelsusCommands($serviceManager);
        
        foreach ($commands as $command) {
            $application->add($command);
        }
    }
}

$application->run();
