<div class="vertical center bg-white column-w4 vertical-bottom no-margin" data-pages="parallax" style="background-image: url('/assets/img/bg-home.jpg'); height: 100vh">
  <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20 full-height">
    <div class="inner text-center p-t-50 m-t-80 full-height" style="transform: translateY(49.3px); opacity: 1;">
      <p class="font-montserrat bold hint-text">NODOS DIGITAL</p>
      <div class="m-b-20">
        <h1 class="text-black inline" style="font-size: 50px">Bienvenido al Admin</h1>
      </div>
      <div class="m-t-20 m-b-40 ">
        <p class="small hint-text">Implementado por <a href="http://www.nodos.pe/" target="_blank">Nodos</a></p>
      </div>
    </div>
  </div>
</div>
