<?php
extract($commonVariables);

// Get names of Tabs with any Element with errors
$tabsWithErrors = array_keys($form->getMessages());
?>

<ul id="tabs" class="nav nav-tabs nav-tabs-linetriangle nav-tabs-separator nav-stack-sm" data-tabs="tabs">
    <?php foreach ($form->getTabList() as $i => $tab): ?>
    <?php $tabName = $tab->getName() ?>
    <li class="<?= ($i == 0 ? 'active' : '') ?>"><a href="#<?= $tab->getName() ?>" data-toggle="tab" class="<?= (in_array($tabName, $tabsWithErrors) ? 'tab-with-error' : '') ?>"><?= $tab->getLabel() ?></a></li>
    <?php endforeach ?>
</ul>

<div id="my-tab-content" class="tab-content">
    <?php foreach ($form->getTabList() as $i => $tab): ?>
    <div class="tab-pane padding-20 <?= ($i == 0 ? 'active' : '') ?>" id="<?= $tab->getName() ?>">
        <?= $this->partial($formParentTabbedContent, compact('tab', 'commonVariables')) ?>
    </div>
    <?php endforeach ?>
</div>

<center><input type="submit" class="btn btn-success" value="Save"></center>
