<?php $vars = $this->viewModel()->getCurrent()->getVariables() ?>
<table class="table table-striped table-bordered">
<thead>
<tr>
    <?php foreach ($provider->getListHeaders() as $header): ?>
    <td>
        <?php
        $vars['header'] = $header;
        echo $this->partial($headerPartial, $vars);
        ?>
    </td>
    <?php endforeach ?>
    <td></td>
</tr>
</thead>

<tbody>
<?php
foreach ($provider->getListRows() as $row) {
    $vars['row'] = $row;
    echo $this->partial($rowPartial, $vars);
}
?>
</tbody>

</table>
