<?php
$queryVars['query'] = ['page' => $page];
?>
<a class="btn btn-primary" href="<?= $this->url($provider->getRoute(), [], $queryVars); ?>">Go back</a>

<?php if($adminCoreService->isAllowed($provider->getResourceName(), 'edit')): ?>
<a class="btn btn-warning"
   href="<?= $this->url($provider->getRoute() . '/edit', ['id' => $id], $queryVars) ?>">
    <i class="glyphicon glyphicon-pencil"></i> Edit
</a>
<?php endif ?>

<h1><?= $provider->getName() ?> - <?= $id ?></h1>

<table class="table table-striped table-bordered model-list">
<tbody>
    <?php foreach($provider->getViewFields() as $providerField): ?>
    <tr><td width="25%">
        <b><?= $providerField->getName() ?></b>
    </td><td valign="top">
        <?= $this->partial('adminauth2/view_value', compact('providerField')) ?>
    </td></tr>
    <?php endforeach ?>
</tbody>
</table>
