<!DOCTYPE html><!--[if lt IE 7]><html id="html" class="no-js lt-ie9 lt-ie8 lt-ie7" lang='es' xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<!--[if IE 7]><html id="html" class="no-js ie7 lt-ie9 lt-ie8" lang='es' xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<!--[if IE 8]><html id="html" class="no-js ie8 lt-ie9" lang="es" xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<!--[if IE 9]><html id="html" class="no-js ie9 lt-ie10" lang="es" xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<html id="html" lang="es">
  <!--<![endif]-->
  <head>
    <title>Registro | Skelsus</title>
    <meta name="description">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, maximum-scale=1, user-scalable=no">
    <meta property="og:title" content="Registro">
    <meta property="og:description">
    <meta property="og:type" content="website">
    <meta property="og:image" content="">
    <link rel="icon" type="image/png" href="<?= $this->basePath().'/site/favicon.ico';?>">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous"><!--[if gte IE 6 & lt IE 9]><script src!="<?php echo $this->basePath() ?>/site/scripts/libs/html5shiv.js"></script><![endif]-->
<!--[if gte IE 6 & lt IE 9]><script src!="<?php echo $this->basePath() ?>/site/scripts/libs/selectivizr.js"></script><![endif]-->
<!--[if lte IE 9]><script> window._ie = true; </script><![endif]-->
    <link href="<?= $this->basePath().'/site/styles/main.css';?>" rel="stylesheet">
    <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      
      ga('create', '', 'auto');
      ga('send', 'pageview');
      
    </script>
  </head>
  <body class="body--register" id="body">
    <div class="Register"><?php $form = $this->form; ?>
<?php $form->setAttribute('id', 'form-register'); ?>
<?php $form->setAttribute('class', 'Register-form'); ?>
<?php $form->setAttribute('action', $this->serverUrl(true)); ?>
<?php $form->setAttribute('data-source-provinces', $this->url('provinces')); ?>
<?php $form->setAttribute('data-source-districts', $this->url('districts')); ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?><?php $e=$form->get('csrf_token'); ?>
<?php echo $this->formInput($e); ?><?php $e=$form->get('first_name'); ?>
<?php $e->setAttribute('class',''); ?>
<?php $e->setAttribute('placeholder',''); ?>
<?php $e->setAttribute('data-rule-maxlength','40'); ?>
<?php $e->setAttribute('data-rule-minlength','0'); ?><?php $e->setAttribute('required','true'); ?><?php echo $this->formInput($e);?>
      <div class="label-errorContent"><?php echo $this->formError($e); ?></div><?php $e=$form->get('last_name'); ?>
<?php $e->setAttribute('class',''); ?>
<?php $e->setAttribute('placeholder',''); ?>
<?php $e->setAttribute('data-rule-maxlength','40'); ?>
<?php $e->setAttribute('data-rule-minlength','0'); ?><?php $e->setAttribute('required','true'); ?><?php echo $this->formInput($e);?>
      <div class="label-errorContent"><?php echo $this->formError($e); ?></div>
      <div class="ElementForm ElementForm--birthday">
        <div class="ElementForm-statement">
          <label class="ElementForm-label" for="birthday">Nacimiento</label><?php $e=$form->get('birthday'); ?>
<?php $e->setAttributes(array('id' => 'birthday','placeholder'=>'','tabIndex'=>'','type'=>'text','class'=>'date ElementForm-input', 'required' => 'true', 'minlength' => '0', 'maxlength' => '11', 'data-rule-mindate' => '01/01/1920', 'data-rule-maxdate' => '01/01/2016' ));?>
<?php echo $this->formInput($e);?>
        </div>
        <div class="ElementForm-errorContent"><?php echo $this->formError($e); ?></div>
      </div><?php $e=$form->get('email'); ?>
<?php $e->setAttribute('class',''); ?>
<?php $e->setAttribute('placeholder',''); ?>
<?php $e->setAttribute('type','email'); ?>
<?php $e->setAttribute('data-rule-maxlength','40'); ?>
<?php $e->setAttribute('data-rule-minlength','0'); ?>
<?php $e->setAttribute('data-reference-confirm',''); ?><?php $e->setAttribute('required','true'); ?><?php echo $this->formInput($e);?>
      <div class="label-errorContent"><?php echo $this->formError($e); ?></div><?php $e=$form->get('document_number'); ?>
<?php $e->setAttribute('pattern','[0-9]*'); ?>
<?php $e->setAttribute('placeholder',''); ?>
<?php $e->setAttribute('class','number '); ?>
<?php $e->setAttribute('data-rule-maxlength','8'); ?>
<?php $e->setAttribute('data-rule-minlength','8'); ?><?php $e->setAttribute('required','true'); ?><?php echo $this->formInput($e);?>
      <div class="label-errorContent"><?php echo $this->formError($e); ?></div><?php $e=$form->get('address'); ?>
<?php $e->setAttribute('class',''); ?>
<?php $e->setAttribute('placeholder',''); ?>
<?php $e->setAttribute('data-rule-maxlength','40'); ?>
<?php $e->setAttribute('data-rule-minlength','0'); ?><?php $e->setAttribute('required','true'); ?><?php echo $this->formInput($e);?>
      <div class="label-errorContent"><?php echo $this->formError($e); ?></div><?php $e=$form->get('telephone'); ?>
<?php $e->setAttribute('pattern','[0-9]*'); ?>
<?php $e->setAttribute('placeholder',''); ?>
<?php $e->setAttribute('class','number '); ?>
<?php $e->setAttribute('data-rule-maxlength','9'); ?>
<?php $e->setAttribute('data-rule-minlength','7'); ?><?php $e->setAttribute('required','true'); ?><?php echo $this->formInput($e);?>
      <div class="label-errorContent"><?php echo $this->formError($e); ?></div><?php $e=$form->get('mobile_phone'); ?>
<?php $e->setAttribute('pattern','[0-9]*'); ?>
<?php $e->setAttribute('placeholder',''); ?>
<?php $e->setAttribute('class','number '); ?>
<?php $e->setAttribute('data-rule-maxlength','9'); ?>
<?php $e->setAttribute('data-rule-minlength','9'); ?><?php $e->setAttribute('required','true'); ?><?php echo $this->formInput($e);?>
      <div class="label-errorContent"><?php echo $this->formError($e); ?></div><?php $e=$form->get('password'); ?>
<?php $e->setAttribute('class',''); ?>
<?php $e->setAttribute('placeholder',''); ?>
<?php $e->setAttribute('type','password'); ?>
<?php $e->setAttribute('data-rule-maxlength','40'); ?>
<?php $e->setAttribute('data-rule-minlength','20'); ?>
<?php $e->setAttribute('data-reference-confirm',''); ?><?php $e->setAttribute('required','true'); ?><?php echo $this->formInput($e);?>
      <div class="label-errorContent"><?php echo $this->formError($e); ?></div><?php $e=$form->get('confirm_password'); ?>
<?php $e->setAttribute('class',''); ?>
<?php $e->setAttribute('placeholder',''); ?>
<?php $e->setAttribute('type','password'); ?>
<?php $e->setAttribute('data-rule-maxlength','40'); ?>
<?php $e->setAttribute('data-rule-minlength','20'); ?>
<?php $e->setAttribute('data-reference-confirm','#password'); ?><?php $e->setAttribute('required','true'); ?><?php echo $this->formInput($e);?>
      <div class="label-errorContent"><?php echo $this->formError($e); ?></div>
      <div class="ElementForm ElementForm--tyc">
        <div class="ElementForm-statement">
          <div class="ElementForm-contentCheckBox">
            <div class="ElementForm-checkBoxIcon"></div><?php $e=$form->get('tyc'); ?>        
<?php $e->setAttributes(array('tabIndex'=>'', 'required' => true, 'id' => 'tyc' ));?>
<?php echo $this->formElement($e); ?>
          </div>
          <label class="ElementForm-label ElementForm-label--checkbox" for="tyc"> Acepto</label><a target="_blank">términos y condiciones</a>
        </div>
        <div class="ElementForm-errorContent"><?php echo $this->formError($e); ?></div>
      </div>
      <div class="ElementForm ElementForm--suscribe">
        <div class="ElementForm-statement">
          <div class="ElementForm-contentCheckBox">
            <div class="ElementForm-checkBoxIcon"></div><?php $e=$form->get('suscribe'); ?>        
<?php $e->setAttributes(array('tabIndex'=>'', 'required' => false, 'id' => 'suscribe' ));?>
<?php echo $this->formElement($e); ?>
          </div>
          <label class="ElementForm-label ElementForm-label--checkbox" for="suscribe"> Acepto suscribirme al boletin</label>
        </div>
        <div class="ElementForm-errorContent"><?php echo $this->formError($e); ?></div>
      </div>
      <input type="submit"><?php echo $this->form()->closeTag(); ?>
    </div>
    <div id="fb-root"></div>
    <script>
      (function(d, u) {
        var s = d.scripts[0],
          i = u.length, g;
        while (i--) {
          if(u[i]) {
            if(u[i]['type'] === 'fb') {
              window.fbAsyncInit = function() {
                FB.init({
                  appId      : '',
                  xfbml      : true,
                  version    : 'v2.0'
                });
              };
            }
            g = d.createElement('script');
            g.async = true;
            g.type = 'text/javascript';
            g.src = '//' + u[i]['url'];
            s.parentNode.insertBefore(g, s);
          }
        }
      }(document, [{'url':'connect.facebook.net/es_ES/sdk.js','type':'fb'},{'url':'platform.twitter.com/widgets.js','type':'tw'}]));
    </script>
  </body>
</html>