<!DOCTYPE html><!--[if lt IE 7]><html id="html" class="no-js lt-ie9 lt-ie8 lt-ie7" lang='es' xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<!--[if IE 7]><html id="html" class="no-js ie7 lt-ie9 lt-ie8" lang='es' xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<!--[if IE 8]><html id="html" class="no-js ie8 lt-ie9" lang="es" xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<!--[if IE 9]><html id="html" class="no-js ie9 lt-ie10" lang="es" xmlns:fb="http://ogp.me/ns/fb#"><![endif]-->
<html id="html" lang="es">
  <!--<![endif]-->
  <head>
    <title>Validación | Skelsus</title>
    <meta name="description">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, maximum-scale=1, user-scalable=no">
    <meta property="og:title" content="Validación">
    <meta property="og:description">
    <meta property="og:type" content="website">
    <meta property="og:image" content="">
    <link rel="icon" type="image/png" href="<?= $this->basePath().'/site/favicon.ico';?>">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous"><!--[if gte IE 6 & lt IE 9]><script src!="<?php echo $this->basePath() ?>/site/scripts/libs/html5shiv.js"></script><![endif]-->
<!--[if gte IE 6 & lt IE 9]><script src!="<?php echo $this->basePath() ?>/site/scripts/libs/selectivizr.js"></script><![endif]-->
<!--[if lte IE 9]><script> window._ie = true; </script><![endif]-->
    <link href="<?= $this->basePath().'/site/styles/main.css';?>" rel="stylesheet">
    <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      
      ga('create', '', 'auto');
      ga('send', 'pageview');
      
    </script>
  </head>
  <body class="body--validator" id="body">
    <main>
      <section>
        <h2>Validator</h2>
      </section>
    </main>
    <div id="fb-root"></div>
    <script>
      (function(d, u) {
        var s = d.scripts[0],
          i = u.length, g;
        while (i--) {
          if(u[i]) {
            if(u[i]['type'] === 'fb') {
              window.fbAsyncInit = function() {
                FB.init({
                  appId      : '',
                  xfbml      : true,
                  version    : 'v2.0'
                });
              };
            }
            g = d.createElement('script');
            g.async = true;
            g.type = 'text/javascript';
            g.src = '//' + u[i]['url'];
            s.parentNode.insertBefore(g, s);
          }
        }
      }(document, [{'url':'connect.facebook.net/es_ES/sdk.js','type':'fb'},{'url':'platform.twitter.com/widgets.js','type':'tw'}]));
    </script>
  </body>
</html>